// Deterministic, dependency-free bundle for the Cloudflare dashboard editor.
import { readFile, mkdir, writeFile } from "node:fs/promises";
const root = new URL("./", import.meta.url);
const privateMode = process.argv.includes("--private");
if (!privateMode) {
  const source = await readFile(new URL("src/aggregate-worker.mjs", root), "utf8");
  await mkdir(new URL("dist/", root), { recursive: true });
  await writeFile(new URL("dist/worker.js", root), source);
  console.log("Built aggregate-only dist/worker.js (no credentials or dashboard).");
} else {
  const files = ["login.html", "dashboard.html", "dashboard.css", "dashboard.js", "login.js"];
  const assets = {};
  for (const file of files) assets[file] = await readFile(new URL(`../web/${file}`, root), "utf8");
  // The Python deployment continues to serve the original shared login page.
  assets["login.html"] = assets["login.html"]
    .replace("自建系统 · 数据保存在你的服务器", "自建系统 · 数据保存在你的 Cloudflare 账户")
    .replace("输入管理员密码，查看你的访问统计。", "输入本地生成的管理员密码，查看你的访问统计。");
  const source = await readFile(new URL("src/worker.mjs", root), "utf8");
  await mkdir(new URL("dist/", root), { recursive: true });
  await writeFile(
    new URL("dist/private-worker.js", root),
    `// Generated by node build.mjs --private. Edit src/worker.mjs or ../web instead.\nconst ASSETS = ${JSON.stringify(assets)};\n${source}`
  );
  console.log("Built optional dist/private-worker.js (requires private-mode secrets).");
}
